name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
permissions:
  contents: read
  pages: write
  id-token: write
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    env:
      FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      FIREBASE_AUTH_ADMIN: ${{secrets.FIREBASE_AUTH_ADMIN}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
      FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: yarn
    - name: Build project
      run: yarn build
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4