name: publish-to-github-pages
on: ['push']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    env:
      FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      FIREBASE_AUTH_ADMIN: ${{secrets.FIREBASE_AUTH_ADMIN}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
      FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
      BASE_PATH: ${{secrets.BASE_PATH}}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn
        
      - name: Build project
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: npx next build

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4